### ISSUE TITLE
"Unexpected token D" Error in Command Builder 

### ISSUE THREAD

**Issue by olakara** [q-nick/npm-gui#10]
When I navigate to the command builder, I keep getting the following error in the console:

> [SyntaxError: Unexpected token D]
> Unhandled rejection TypeError: Cannot read property 'length' of undefined
>     at Object.t [as buildObjectFromArray](D:nodejsnode_modulesnpm-guinpm-gui.js:19:415)
>     at D:\nodejs\node_modules\npm-gui\npm-gui.js:206:3591
>     at i (D:\nodejs\node_modules\npm-gui\npm-gui.js:1:888)
>     at i._settlePromiseFromHandler (D:\nodejs\node_modules\npm-gui\npm-gui.js:207:19369)
>     at i._settlePromise (D:\nodejs\node_modules\npm-gui\npm-gui.js:207:20172)
>     at i._settlePromise0 (D:\nodejs\node_modules\npm-gui\npm-gui.js:207:20873)
>     at i._settlePromises (D:\nodejs\node_modules\npm-gui\npm-gui.js:207:22203)
>     at i._drainQueue (D:\nodejs\node_modules\npm-gui\npm-gui.js:206:7831)
>     at i._drainQueues (D:\nodejs\node_modules\npm-gui\npm-gui.js:206:7892)
>     at Immediate.drainQueues [as _onImmediate](D:nodejsnode_modulesnpm-guinpm-gui.js:206:5943)
>     at processImmediate [as _immediateCallback](timers.js:383:17)

**Comment by q-nick** [comment]
Command builder is in strong beta ;)

Anyway thanks for feedback!
