### ISSUE TITLE
the source code of the npm-gui is published under the ISC license?

### ISSUE THREAD

**Issue by FLWryoko** [q-nick/npm-gui#11]
Hello,
 As with [the npm-gui package](https://www.npmjs.com/package/npm-gui) on npmjs.com,
 [the source code of the npm-gui](https://github.com/q-nick/npm-gui)  is published under the ISC  license?

**Comment by q-nick** [comment]
Hi @ryoheiwn 
Formally yes - ISC is default license in npm package.json generator.

Could you tell me why should I change that? I can release next version with... hmm  - MIT license?

**Comment by ryoheiwn** [comment]
Thank you @q-nick .
I think the MIT license is suitable for next version,because popular and lenient.
