### ISSUE TITLE
spawn error

### ISSUE THREAD

**Issue by gaowhen** [q-nick/npm-gui#13]
I installed it locally in one project on Mac.

```
npm-gui panel running at http://0.0.0.0:1337/


I will be waiting here to help you with your work with pleasure.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/path/to/node_modules/npm-gui/node_modules/nsp/bin/nsp ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

```
node -v
v4.2.1
npm -v
3.8.3
```

**Comment by q-nick** [comment]
@gaowhen Hi. Unfortunately I started refactoring whole app and it will be hard to make an hotfix.

It seems that `nsp` command doesn't works. For now I can suggest you to install `npm-gui` globally or if the rest of app works properly just don't care about that error.

Ofcourse I will take a look on that issue in current development version. Thank for your feedback. I will notice you when I'll figure it out.
