### ISSUE TITLE
console output almost unreadable

### ISSUE THREAD

**Issue by tx4x** [q-nick/npm-gui#16]
Maybe its just me, but your console output is way to bright, a pita to read :-)

**Comment by q-nick** [comment]
Hi, currently I'm working on new version of npm-gui. Do you have any specific suggestions about console?

**Comment by xblox** [comment]
i just noticed its hard to read (having good screens here). but yeah, here you go:

- support colors (there is ANSI 2 HTML somewhere)
- would be cool if that left/main would be resizable

and something I always wanted: being able to update dependencies on multiple directories. not sure how his could work, though.

thanks for the heads up !
