### ISSUE TITLE
modules with `@name/` prefix show as `missing`

### ISSUE THREAD

**Issue by Fjandin** [q-nick/npm-gui#30]
![image](https://user-images.githubusercontent.com/167869/54814794-b78d4080-4c90-11e9-8f3b-fc291938136d.png)

Seems all my modules that have `@name` prefix show as missing even though they are installed.

I'm on `npm-gui@2.0.1` and using `yarn@1.15.2`

**Comment by q-nick** [comment]
Thanks. I'll check it.
