### ISSUE TITLE
Add visual indicator for unused packages

### ISSUE THREAD

**Issue by smeijer** [q-nick/npm-gui#31]
The one thing that this package is missing, that would make it truly awesome (IMO).

A visual indicator if the package seems to be unused. It doesn't need to be a guarantee. I think a quick scan for `imports` or `requires` would be sufficient.

The further analyses could be done manually.

About visual indicators. "dependency" / "devDependency" hinting would be useful as well. Babel and Eslint plugins, are usually defined as `dev-dependency`. A hint like: "shouldn't this be a dev-dependency?", (or the opposite) would be very useful for starting developers.

**Comment by q-nick** [comment]
Accepted feature suggestions moved to README

**Comment by smeijer** [comment]
I've created `unimported` somewhere back in 2021. Perhaps it can be of value if/when this feature gets implemented.

https://github.com/smeijer/unimported
