### ISSUE TITLE
[request] Management of global packages

### ISSUE THREAD

**Issue by fubarhouse** [q-nick/npm-gui#4]
I'm keen to use this, but I've noted it doesn't support the management of globally installed packages.
If this feature was to be in there, I could use this as a full-time management application.

Otherwise, I am very happy to use it for it's purpose, but it's not scalable at this point.

**Comment by q-nick** [comment]
@fubarhouse that's cool - management for global package will appear in next release.

**Comment by fubarhouse** [comment]
The ability to also pick and choose a package.json file from a particular folder or json entry for a path would also be quite useful but more on the want side than a need.

Thanks for that info though, I will be sure to check back for updates :)

**Comment by q-nick** [comment]
https://github.com/q-nick/npm-gui/issues/5

**Comment by q-nick** [comment]
@fubarhouse version v0.3.0 contain feature that you requested. Would you like to confirm that it works?

**Comment by fubarhouse** [comment]
That, is working nicely. Thank you :)
