### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by mreis1** [q-nick/npm-gui#57]
Hello guys, first of all, thanks for this cool project 😉.
I came by to share some ideas for future versions if you decide to consider them. 

1) Show release date on each module version (per column - latest, compatible, current). Maybe in small letters with low contrast under the version badge? 

2) Don't know if the purpose of "NPM" badge is to be clicked or not. In my case, clicking it does nothing but I expected it to open the npm project's page. 

3) Similarly to the npm icon, we could have a repo icon, that clicking would take us the the bitbucket / github project

4) Dynamic columns: we could re-arrange existing columns (drag and drop) and toggle extra columns that could bring information such as module description, author, release date, last commit, and display the dates I mentioned previously in their own data columns which would be handy for sorting.  

5) While browsing file system allow filtering: 
![image](https://user-images.githubusercontent.com/1719667/160667933-f6f6e181-97a0-4b56-a314-fc39ae336be4.png)

6) Each module could be expanded/collapsable to reveal it's dependency tree 
![image](https://user-images.githubusercontent.com/1719667/160668965-0bc35d08-5b13-4544-aacc-6e3077bf093b.png)

Here's a tree generated with `npm-remote-ls serialport@8.0.7` that I used as an example here:  https://pastebin.com/duqQDWLu

**Comment by q-nick** [comment]
Accepted feature suggestions moved to README
