### ISSUE TITLE
Span error on launch

### ISSUE THREAD

**Issue by TimmyParkwayd** [q-nick/npm-gui#6]
I'd like to test it for my many projects on Node, the problem is I got an error on the moment I access it from my browser

```
npm-gui panel running at http://0.0.0.0:1337/


I will be waiting here to help you with your work with pleasure.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:896:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by q-nick** [comment]
Could you tell me:
0. Windows or linux?
1. How you install `npm-gui` - global or local?
2. Result of: `npm -v`
3. Result of: `node -v`

thanks!

**Comment by TimmyParkwayd** [comment]
I wanna launch it on a Windows 7 OS

  1. My npm-gui package is global
  2.  ``λ npm -v : 
3.8.6``
  3. ``λ node -v : 
v6.0.0 ``

Is it a recurrent problem on win?

Thx in advance !

**Comment by q-nick** [comment]
I think - it is not recurrent problem, but a new problem - on win ;)
I will try to figure it out asap.

Big thanks for feedback!

**Comment by TimmyParkwayd** [comment]
No problems !
The app seems really cool, I'd really like to try it :)

Good luck with it !

**Comment by leebivip** [comment]
Me too!
npm-gui localhost:2051
npm-gui panel running at http://localhost:2051/


I will be waiting here to help you with your work with pleasure.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

D:\env\cmder/vendor/clink-completions/npm_prompt.lua:11: attempt to concatenate local 'package_versivalue) nil


 node -v
v6.1.0
npm -v
3.9.2
Windows 10

But.The app seems really cool!

**Comment by amgadfahmi** [comment]
+1
```
npm 3.9.0 
node 4.4.0 
windows 10 
installed globally 
```

**Comment by q-nick** [comment]
@TimmyParkwayd @leebivip @amgadfahmi Hi guys, version 0.3.1 contain bugfix would you like to confirm that everything works?
Thanks.
