### ISSUE TITLE
Just some ideas ;)

### ISSUE THREAD

**Issue by aersam** [q-nick/npm-gui#61]
Wouldn't it be great to have npm-gui integrated into VS Code as an Extension? That would be so awesome! 

Also would it be possible in theory to add completely different Package Managers? Say: poetry (python) or nuget (.net)? You're only executing commands, so seems to be very simple and nice design for any package manager

**Comment by q-nick** [comment]
@aersamkull  Hi! 

Thanks for the feedback ;) I think that integration with VSCode might be tricky, extensions for VSCode are very specific, and this might require a completely new approach. 
But the second suggestion about other package managers is very interesting. Currently, I'm focusing on integration with yarn and pnpm and maybe other package managers for javascript. I will consider integration for a completely new environment as you mention ;)

**Comment by aersamkull** [comment]
I might be interested in implementing poetry as it has no decent GUI yet. We'll see :)

**Comment by q-nick** [comment]
Accepted feature suggestions moved to README
