### ISSUE TITLE
Electron App?

### ISSUE THREAD

**Issue by bnb** [q-nick/npm-gui#8]
Hello.

Was just wondering if you have considered an electron app? With all the work you've done, it seems like it should be fairly simple. 

I'd also like to assist if there is anything I can do with this project as a whole.

**Comment by bnb** [comment]
Ah, I see that there's an electron folder in the repo. Have you gone through packaging with it?

**Comment by q-nick** [comment]
Yes, electron binary will be available soon. 
But first i need to figure how to do self-update **npm-gui** to newest version.

**Comment by bnb** [comment]
[This](http://electron.atom.io/community/) page has some options:

[Electron Release Server](https://github.com/ArekSredzki/electron-release-server)
[Electron gh-releases](https://github.com/jenslind/electron-gh-releases)
[Electron updater](https://github.com/evolvelabs/electron-updater)
[Nuts](https://github.com/GitbookIO/nuts)

**Comment by q-nick** [comment]
@bnb would you like to prepare everything that is required to build electron app binary?

As i see - releases (and later updates) could be served directly from github repo? 


In project there is command to serve **npm-gui** on prebuilt electron, you should:
`git clone`
`npm install`
`npm run app`
then app window should appear.

Binary will also required to add: #5 - but i can handle this.

Also will be nice to do some automatic tests which could determine that new binary is working on Linux, Windows and OSX.

**Comment by bnb** [comment]
I seem to have gotten the electron-gh-releases plugin to work, being served directly from GitHub. No idea how to add tests for that if they're needed. Looking into building an app binary for multiple platforms.

**Comment by q-nick** [comment]
Don't worry about test right now, they could be added later.
